config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'application#index'
  get '/exam', to: 'exam#index'
  get '/exam/:n', to: 'exam#index', as: :examwithlevel
  namespace :admin do
    get '/', to: 'admin#index'
    resources :question, only: [:index, :new, :create, :edit, :update]
    post '/questiondelete/:id', to: 'question#destroy', as: :question_delete
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :omniauthable,
         omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    # Create user if new?
    user = User.prepare_user(data) unless user
    user.token = access_token['credentials']['token']
    user.save
    user
  end

  def self.prepare_user(data)
    User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_action :authenticate_user!, :check_admin

    layout 'admin'

    def index; end

    private

    def check_admin
      return unless current_user.email != 'admin@admin.com'
      redirect_to root_path, flash: { error: 'Insufficient rights!' }
    end
  end
end

app/controllers/admin/question_controller.rb
class Admin::QuestionController < Admin::AdminController
  skip_before_filter :verify_authenticity_token

  def index
    @questions = Question.all.includes(:answers)
  end

  def new
    @path = admin_question_index_url
    @redirectpath = admin_question_index_url
  end

  def create
    ActiveRecord::Base.transaction do
      question = Question.new({
        name: params['question'],
        description: '',
        qtype: params['question_type'],
        test_level: params['question_level']
      })
      for i in params['answers'] do
        Answer.create({
          name: i['answer'],
          description: '',
          question: question,
          correct: i['correct']
        })
      end
      render nothing: true, status: 200, content_type: 'application/json'
    end
  end

  def edit
    @question = Question.find(params['id'])
    @path = admin_question_url(@question)
    @redirectpath = admin_question_index_url
  end

  def update
    ActiveRecord::Base.transaction do
      question = Question.update(
        params['id'],
        name: params['question'],
        qtype: params['question_type'],
        test_level: params['question_level']
      )
      params['answers'].each do |answer|
        if answer['markdelete']
          Answer.destroy(answer['id'])
        else
          if answer['id'] > 0
            Answer.update(
              answer['id'],
              name: answer['name'],
              correct: answer['correct']
            )
          else
            Answer.create({
              name: answer['name'],
              correct: answer['correct'],
              description: '',
              question: question
            })
          end
        end
      end
      render nothing: true, status: 200, content_type: 'application/json'
    end
  end

  def destroy
    Question.destroy(params['id'].to_i)
    redirect_to admin_question_index_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index; end
end

app/controllers/exam_controller.rb
class ExamController < ApplicationController
  before_action :authenticate_user!

  def index
    @exam = Question.where(test_level: 4).includes(:answers)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < ApplicationController
    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        user_persisted
      else
        user_not_persisted
      end
    end

    private

    def user_persisted
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    end

    def user_not_persisted
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages
    end
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/question_helper.rb
module Admin::QuestionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/admin/admin/index.html.erb
<h1><strong><i class='fa fa-tachometer'></i> Admin Dashboard</strong></h1>
<hr>
<div class='row'>
  <!-- center left-->
  <div class='col-md-6'>
    <h3><strong>TODO</strong></h3>
    <ul>
      <li>
        More polish!
      </li>
      <li>
        Better UI/UX
      </li>
      <li>
        Listening Exam
      </li>
    </ul>
    <hr/>
    <div class='table-responsive'>
      <table class='table table-striped'>
        <thead>
        <tr>
          <th>Statistics</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><strong>Question</strong></td>
          <td><%= Question.count %></td>
        </tr>
        <tr>
          <td><strong>User</strong></td>
          <td><%= User.count %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!--/col-->
  <div class='col-md-6'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h4><strong>Notices</strong></h4>
      </div>
      <div class='panel-body'>
        <p>This is a prototype Japanese examination Web Application.</p>
        <p>I have been given so much afford into these thing.</p>
        <p>I hope it helps!</p>
        <p class='text-right'>Bruno</p>
      </div>
    </div>
  </div>
  <!--/col-span-6-->
</div>
<!--/row-->

app/views/admin/question/edit.html.erb
<section ng-controller='EditQuestionCtrl'>
  <div class='row'>
    <div class='container-fluid'>
      <div class='pull-left'>
        <h1><strong><i class='fa fa-database'></i> Manage Questions // Edit Question</strong></h1>
      </div>
      <div class='pull-right'>
        <%= link_to 'Back', admin_question_index_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <hr/>
  <div class='row'>
    <div class='container-fluid'>
      <h3><strong>Question Section</strong></h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-3'>
      <h4>Question type:</h4>
    </div>
    <div class='col-sm-3'>
      <div class='form-group'>
        <select class='form-control' ng-model='postdata.question_type'>
          <option ng-value='1'>Vocabulary</option>
          <option ng-value='2'>Kanji</option>
          <option ng-value='3'>Grammar</option>
          <option ng-value='4'>Listening</option>
        </select>
      </div>
    </div>
    <div class='col-sm-3'>
      <h4>Question level:</h4>
    </div>
    <div class='col-sm-3'>
      <div class='form-group'>
        <select class='form-control' ng-model='postdata.question_level'>
          <option ng-value='4'>N4</option>
          <option ng-value='3'>N3</option>
          <option ng-value='2'>N2</option>
          <option ng-value='1'>N1</option>
        </select>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-3'>
      <h4>Question input:</h4>
    </div>
    <div class='col-sm-9'>
      <div text-angular ng-model='postdata.question' ta-toolbar='[["bold","italics","underline",],["insertImage","insertLink"],["html"]]'></div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-3'>
      <h4>Question output:</h4>
    </div>
    <div class='col-sm-9'>
      <div ta-bind ng-model='postdata.question'></div>
    </div>
  </div>
  <hr/>
  <div class='row'>
    <div class='container-fluid'>
      <div class='pull-left'>
        <h3><strong>Answer Section</strong></h3>
      </div>
      <div class='pull-right'>
        <a class='btn btn-warning' ng-click='addAnswer()'>Add Answer</a>
      </div>
    </div>
  </div>
  <div class='container-fluid' ng-repeat='i in postdata.answers' ng-hide='i.markdelete'>
    {{ i.markdelete }}
    <hr/>
    <h4><strong>Answer #{{ $index + 1 }} </strong>
      <a class='btn btn-delete pull-right' ng-click='removeAnswer($index, i)'> remove </a>
    </h4>

    <div class='row'>
      <div class='col-sm-3'>
        <h4>Correct answer:</h4>
      </div>
      <div class='col-sm-9'>
        <div class='checkbox'>
          <label><input type='checkbox' ng-checked='i.correct' ng-model='i.correct'>This is correct answer</label>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-sm-3'>
        <h4>Question input:</h4>
      </div>
      <div class='col-sm-9'>
        <input type='text' class='form-control' ng-model='i.name'>
      </div>
    </div>
  </div>
  <hr/>
  <div class='row text-center paddding-bottom-15'>
    <a class='btn btn-success btn-lg' ng-click='editQuestion()'>Edit Question</a>
  </div>
  <script type='text/ng-template' id='editSuccess'>
    <div class='row'>
      <div class='container'>
        <h1><strong>Edit Question finished!</strong></h1>
      </div>
    </div>
    <div class='row'>
      <div class='container-fluid'>
        <div class='text-right'>
          <a class='btn btn-danger' ng-click='closeThisDialog()'>Close</a>
        </div>
      </div>
    </div>
  </script>
  <script type='text/ng-template' id='editNotSuccess'>
    <div class='row'>
      <div class='container'>
        <h1>Question<strong>can not</strong> be edited!</h1>
      </div>
    </div>
    <div class='row'>
      <div class='container-fluid'>
        <div class='text-right'>
          <a class='btn btn-danger' ng-click='closeThisDialog()'>Close</a>
        </div>
      </div>
    </div>
  </script>
  <div id='div-data' data-path='<%= @path %>' data-redirect-path='<%= @redirectpath %>' data-question='<%= @question.to_json(include: :answers) %>' class='hidden'></div>
</section>

app/views/admin/question/index.html.erb
<section ng-controller='QuestionCtrl'>
  <div class='row'>
    <div class='container-fluid'>
      <div class='pull-left'>
        <h1><strong><i class='fa fa-database'></i> Manage Questions</strong></h1>
      </div>
      <div class='pull-right'>
        <%= link_to 'New Question', new_admin_question_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <hr/>
  <div ng-repeat='exam in examdata' class='exam'>
    <div class='container-fluid'>
      <div class='panel panel-primary'>
        <div class='panel-heading'>
          <ul class='list-inline margin-bottom-0'>
            <li class='list-inline-item'>
              <div><p>#{{ exam.id }} [N{{ exam.test_level }}]</p></div>
              <div><p></p></div>
            </li>
            <li class='list-inline-item'>
              <div ng-bind-html='exam.name'></div>
            </li>
            <li class='list-inline-item pull-right'>
              <%= link_to 'Edit', URI::unescape(edit_admin_question_url('{{exam.id}}')), class: 'btn btn-warning' %>
              <%= link_to 'Delete', URI::unescape(admin_question_delete_url('{{exam.id}}')), class: 'btn btn-danger', method: :post, data: {confirm: 'Are you sure?'} %>
            </li>
          </ul>
        </div>
        <div class='panel-body'>
          <div ng-repeat='answer in exam.answers'>
            <i class='fa fa-circle-o fa-2x'> {{answer.name}}</i>
            <i class='fa fa-check fa-2x' ng-if='answer.correct'></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id='div-data' data-exam='<%= @questions.to_json(include: :answers) %>' data-delete-path='<%= @delete_path %>' class='hidden'></div>
</section>

app/views/admin/question/new.html.erb
<section ng-controller="NewQuestionCtrl">
  <div class="row">
    <div class="container-fluid">
      <div class="pull-left">
        <h1><strong><i class="fa fa-database"></i> Manage Questions // New Question</strong></h1>
      </div>
      <div class="pull-right">
        <%= link_to 'Back', admin_question_index_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="container-fluid">
      <h3><strong>Question Section</strong></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <h4>Question type:</h4>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <select class="form-control" ng-model="postdata.question_type">
          <option ng-value="1">Vocabulary</option>
          <option ng-value="2">Kanji</option>
          <option ng-value="3">Grammar</option>
          <option ng-value="4">Listening</option>
        </select>
      </div>
    </div>
    <div class="col-sm-3">
      <h4>Question level:</h4>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <select class="form-control" ng-model="postdata.question_level">
          <option ng-value="4">N4</option>
          <option ng-value="3">N3</option>
          <option ng-value="2">N2</option>
          <option ng-value="1">N1</option>
        </select>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <h4>Question input:</h4>
    </div>
    <div class="col-sm-9">
      <div text-angular ng-model="postdata.question" ta-toolbar="[['bold','italics','underline',],['insertImage','insertLink'],['html']]"></div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <h4>Question output:</h4>
    </div>
    <div class="col-sm-9">
      <div ta-bind ng-model="postdata.question"></div>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="container-fluid">
      <div class="pull-left">
        <h3><strong>Answer Section</strong></h3>
      </div>
      <div class="pull-right">
        <a class="btn btn-warning" ng-click="addAnswer()">Add Answer</a>
      </div>
    </div>
  </div>
  <div class="container-fluid" ng-repeat="i in postdata.answers">
    <hr/>
    <h4><strong>Answer #{{ $index + 1 }} </strong>
      <a class="btn btn-delete pull-right" ng-click="removeAnswer($index)"> remove </a>
    </h4>
    <div class="row">
      <div class="col-sm-3">
        <h4>Correct answer:</h4>
      </div>
      <div class="col-sm-9">
        <div class="checkbox">
          <label><input type="checkbox" ng-checked="i.correct" ng-model="i.correct">This is correct answer</label>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <h4>Question input:</h4>
      </div>
      <div class="col-sm-9">
        <input type="text" class="form-control" ng-model="i.answer">
      </div>
    </div>
  </div>
  <hr/>
  <div class="row text-center paddding-bottom-15">
    <a class="btn btn-success btn-lg" ng-click="createNewQuestion()">Create New Question</a>
  </div>
  <script type="text/ng-template" id="createdSuccess">
    <div class="row">
      <div class="container">
        <h1><strong>New Question created!</strong></h1>
      </div>
    </div>
    <div class="row">
      <div class="container-fluid">
        <div class="text-right">
          <a class="btn btn-danger" ng-click="closeThisDialog()">Close</a>
        </div>
      </div>
    </div>
  </script>
  <script type="text/ng-template" id="createdNotSuccess">
    <div class="row">
      <div class="container">
        <h1>Question<strong>can not</strong> be created!</h1>
      </div>
    </div>
    <div class="row">
      <div class="container-fluid">
        <div class="text-right">
          <a class="btn btn-danger" ng-click="closeThisDialog()">Close</a>
        </div>
      </div>
    </div>
  </script>
  <div id="div-data" data-path="<%= @path %>" data-redirect-path="<%= @redirectpath %>" class="hidden"></div>
</section>

app/views/application/index.html.erb
<section class="landing">
  <div class="container">
    <div class="row paddding-bottom-15">
      <%= image_tag 'japanflag', class: 'japanese-flag' %>
      <h2><strong>Japanese Test</strong></h2>
    </div>
    <div class="row paddding-bottom-15">
      <%= link_to 'Try <strong>N4</strong> questions'.html_safe, examwithlevel_path('n4'), class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html ng-app='App'>
<head>
  <title>Minnano</title>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
  <%= stylesheet_link_tag 'application' %>
</head>
<body>
<div class='navbar navbar-inverse navbar-static-top'>
  <div class='container-fluid background-container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to 'Dashboard', admin_question_index_path, :class => 'navbar-brand' %>
    </div>
    <div class='navbar-collapse collapse'>
      <ul class='nav navbar-nav navbar-right'>
        <li><a>Hello, <%= current_user.email %></a></li>
        <li><%= link_to('<i class="fa fa-home"></i> Home'.html_safe, root_path) %></li>
        <li><%= link_to('<i class="fa fa-sign-out"></i> Logout'.html_safe, destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div>
  </div>
</div>
<div class='container-fluid background-container'>
  <div class='row'>
    <div class='col-sm-3'>
      <a href='#'><strong><i class='glyphicon glyphicon-wrench'></i> Menu</strong></a>
      <hr>
      <ul class='nav nav-stacked'>
        <li><%= link_to '<i class="fa fa-tachometer"></i> Admin Dashboard'.html_safe, admin_path %></li>
        <li><%= link_to '<i class="fa fa-database"></i> Manage Questions'.html_safe, admin_question_index_path %></li>
      </ul>
    </div>
    <div class='col-sm-9'>
      <%= yield %>
    </div>
  </div>
</div>
</body>
<%= javascript_include_tag 'application' %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='App'>
<head>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
  <%= stylesheet_link_tag 'application' %>
  <title>Quiz</title>
</head>
<body>
<div class='wrapper'>
  <div class='header'>
    <nav class='navbar navbar-default'>
      <div class='container'>
        <div class='navbar-header'>
          <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar'>
            <span class='sr-only'>Toggle navigation</span><i class='fa fa-bars'></i>
          </button>
          <%= link_to 'Quiz', root_path, class: 'navbar-brand' %>
        </div>
        <div class='collapse navbar-collapse' id='navbar'>
          <ul class='nav navbar-nav navbar-right'>
            <% if (user_signed_in? and current_user.email.to_s == 'admin@admin.com') %>
                <li>
                  <a>
                    Hello, <%= current_user.email %>
                  </a>
                </li>
                <li>
                  <%= link_to '<i class="fa fa-tachometer"></i> Admin Dashboard'.html_safe, admin_path %>
                </li>
                <li>
                  <%= link_to '<i class="fa fa-sign-out"></i> Sign out'.html_safe, destroy_user_session_path, :method => :delete %>
                </li>
            <% elsif user_signed_in? %>
                <li>
                  <a>
                    Hello, <%= current_user.email %>
                  </a>
                </li>
                <li>
                  <%= link_to '<i class="fa fa-sign-out"></i> Sign out'.html_safe, destroy_user_session_path, :method => :delete %>
                </li>
            <% else %>
                <li>
                  <%= link_to '<i class="fa fa-sign-in"></i> Sign in'.html_safe, new_user_session_path %>
                </li>
                <li>
                  <%= link_to '<i class="fa fa-id-card"></i> Sign up'.html_safe, new_user_registration_path %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class='body'>
    <%= yield %>
  </div>
  <div class='footer'>
    <div class='container'>
      <p>© 2017 • pongpolb .</p>
      <ul class='list-inline'>
        <li>
          <a href='https://www.facebook.com/pongpolb'><i class='fa fa-facebook-official' aria-hidden='true'></i></a>
        </li>
        <li>
          <a href='https://github.com/pongpolb'><i class='fa fa-github' aria-hidden='true'></i></a>
        </li>
      </ul>
    </div>
  </div>
</div>
<%= javascript_include_tag 'application' %>
</body>
</html>